### ISSUE TITLE
Maybe there is an security issue?

### ISSUE THREAD

**Issue by csr632** [cornflourblue/mean-angular2-registration-login-example#1]
In _function update(req, res)_ from _/server/controllers/users.controller.js_ , you pass req.params._id to the userService, but never check whether req.params._id === req.user.sub. Maybe Peter can use his token to update Mary's data by http.put(this.config.apiUrl + '/users/' + **Mary's _id**, **Peter's jwt**).
Thank you for your great tutorial！I am a new hand and your tutorial help me a lot!

**Comment by cornflourblue** [comment]
I intentionally made the api controller and service minimal so they could be used as boilerplate code without any assumptions about business rules / validation. There could be scenarios where users are allowed to update other user details (e.g. administrators), specific application logic like this should be added where necessary.
