### ISSUE TITLE
How to run it on localhost?

### ISSUE THREAD

**Issue by WebTalentTop** [cornflourblue/mean-angular2-registration-login-example#3]
I have no idea how to run it.
It is separated as server side and client side so Do I have to npm install 2 times?
And then what should be next step to run it wihtout any issue?
Please help me.

**Comment by cornflourblue** [comment]
For details and documentation go to http://jasonwatmore.com/post/2017/02/22/mean-with-angular-2-user-registration-and-login-example-tutorial
